
import React from 'react';
import { BehavioralInsight } from '../types';
import { Sparkles, Brain, TrendingUp, AlertCircle, RefreshCcw } from 'lucide-react';
import { Language, translations } from '../translations';

interface Props {
  insights: BehavioralInsight[];
  loading: boolean;
  onRefresh: () => void;
  lang: Language;
}

const InsightIcon = ({ type }: { type: string }) => {
  switch (type) {
    case 'pattern': return <TrendingUp className="w-5 h-5" />;
    case 'psychology': return <Brain className="w-5 h-5" />;
    case 'budget': return <AlertCircle className="w-5 h-5" />;
    default: return <Sparkles className="w-5 h-5" />;
  }
};

const AIInsights: React.FC<Props> = ({ insights, loading, onRefresh, lang }) => {
  const t = translations[lang];
  return (
    <div className="bg-gradient-to-br from-indigo-50 via-white to-blue-50 rounded-2xl p-6 border border-blue-100 shadow-sm relative overflow-hidden">
      <div className={`absolute top-0 ${lang === 'ar' ? 'left-0' : 'right-0'} p-8 opacity-5`}>
        <Sparkles className="w-32 h-32 text-blue-600" />
      </div>
      
      <div className="flex justify-between items-center mb-6 relative">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-600 rounded-lg text-white">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-gray-800">{t.behavioral_insights}</h2>
            <p className="text-xs text-gray-500">{t.ai_analysis_sub}</p>
          </div>
        </div>
        
        <button 
          onClick={onRefresh}
          disabled={loading}
          className="flex items-center gap-2 text-xs font-semibold text-blue-600 hover:text-blue-700 disabled:opacity-50 transition-colors"
        >
          <RefreshCcw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          {t.refresh_analysis}
        </button>
      </div>

      {loading ? (
        <div className="space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-20 bg-white/50 animate-pulse rounded-xl border border-gray-100"></div>
          ))}
        </div>
      ) : (
        <div className="space-y-4 relative">
          {insights.length === 0 ? (
            <p className="text-center text-gray-500 py-8 italic">
              {t.analyze_more}
            </p>
          ) : (
            insights.map((insight, idx) => (
              <div 
                key={idx} 
                className={`flex gap-4 p-4 rounded-xl border transition-all hover:scale-[1.01] ${
                  insight.severity === 'warning' 
                    ? 'bg-amber-50/50 border-amber-100' 
                    : insight.severity === 'positive'
                    ? 'bg-emerald-50/50 border-emerald-100'
                    : 'bg-white/80 border-gray-100 shadow-sm'
                }`}
              >
                <div className={`mt-0.5 p-2 rounded-lg shrink-0 h-fit ${
                   insight.severity === 'warning' ? 'text-amber-600 bg-amber-100' :
                   insight.severity === 'positive' ? 'text-emerald-600 bg-emerald-100' :
                   'text-blue-600 bg-blue-50'
                }`}>
                  <InsightIcon type={insight.type} />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-gray-800 mb-1">{insight.title}</h4>
                  <p className="text-sm text-gray-600 leading-relaxed">{insight.description}</p>
                </div>
              </div>
            ))
          )}
        </div>
      )}
      
      <div className="mt-6 pt-6 border-t border-blue-100/50 flex items-center justify-between text-[10px] text-gray-400 font-medium uppercase tracking-widest">
        <span>{lang === 'ar' ? 'محرك التعليقات المحايد v1.0' : 'Neutral Feedback Engine v1.0'}</span>
        <span>{lang === 'ar' ? 'بواسطة Gemini Flash' : 'Generated by Gemini Flash'}</span>
      </div>
    </div>
  );
};

export default AIInsights;
